.TH BDSIM "1" "May 2018" "bdsim 0" "User Commands"
.SH NAME
bdsim \- a library to simulate block devices in test suites
.SH SYNOPSIS
.B LD_PRELOAD=libbdsim.so LIBBDSIM_CONFIG=bdsim.cfg LIBBDSIM_SYSFS=/path/to/fake/sys/
.SH DESCRIPTION
.PP
\fBbdsim\fR is a library which intercepts system calls to block devices and
replaces them with simulated versions.
.SH "BUGS"
.PP
Please direct any bugs, features, patches, etc. to the Red Hat bootloader team
at https://github.com/rhboot/bdsim \&.
